const CLEARANCE_LEVELS = {
  GENERAL_NEWBIE: 'GENERAL_NEWBIE',
  PERMANENT_STAFF: 'PERMANENT_STAFF',
  CONFIDENTIAL_ADMIN: 'CONFIDENTIAL_ADMIN'
};

const CLEARANCE_RANK = {
  [CLEARANCE_LEVELS.GENERAL_NEWBIE]: 1,
  [CLEARANCE_LEVELS.PERMANENT_STAFF]: 2,
  [CLEARANCE_LEVELS.CONFIDENTIAL_ADMIN]: 3
};

const CONTENT_TYPES = {
  ONBOARDING_GUIDE: 'ONBOARDING_GUIDE',
  POST_MORTEM_ERROR: 'POST_MORTEM_ERROR'
};

const SOURCE_STATUS = {
  ACTIVE: 'ACTIVE',
  ARCHIVED: 'ARCHIVED',
  DEPRECATED: 'DEPRECATED',
  PENDING_PROCESSING: 'PENDING_PROCESSING'
};

module.exports = {
  CLEARANCE_LEVELS,
  CLEARANCE_RANK,
  CONTENT_TYPES,
  SOURCE_STATUS
};
